### PR TITLE
start behave test suite

### PR DESCRIPTION
**Pull request by fbenkstein**
Start of a BDD tests suite for the bot's behavior.  There's only one feature at the moment, testing enabling and disabling (and getting a Code-Review+2 message).  There's no clean up yet so it spams the Gerrit server with changes.  This shouldn't be a problem though, when running against the docker container.

### CODE REVIEW

**Comment by fbenkstein** [comment]
I'm going to split this up into multiple PRs:  one for the `gerritbot-console`, one for `behave` and one where I'll try to get `behave` into travis.  You could tell me what you think of the general shape of it, if you have some time, though.

**Comment by gferon** [comment]
I guess you probably want to close this one, then?

**Comment by fbenkstein** [comment]
> I guess you probably want to close this one, then?

No, the PRs are based on each other.  Haven't found a way to make this obvious in the github UI.

**Comment by fbenkstein** [comment]
Rebased.

**Comment by gferon** [comment]
I kinda feel this is way overkill for what we're doing here but... also, I'd rather have all of this in `rust` and not depend on a 3rd party framework, but let's keep our minds open for such experiments :smile:

**Pull request merged**
