### PR TITLE
Remove experimental lua.

### PR DESCRIPTION
**Pull request by boxdot**

### CODE REVIEW

**Comment by fbenkstein** [comment]
Why?

**Comment by gferon** [comment]
We kind of felt it defeats the purpose of everything that rust brings, and we looked at the code and it doesn't really bring any useful customization features. My question to you is more: why not? Do you have any reason/future use case why we shouldn't remove it?

**Comment by fbenkstein** [comment]
To me it made sense to put the formatting outside so it can be changed without having to recompile.  I would like to have more policy on the lua side, where it can be easily changed.  I can imagine the lua code not only being responsible for formatting but also for deciding whether a message should be sent or not.  Unfortunately, it's difficult to run my own instance.  When there's only one instance customization doesn't really make sense.  So, I agree with making the code simpler.  Go ahead.

**Comment by boxdot** [comment]
@fbenkstein, I really get your point, since the idea to bring in Lua was exactly due to the use case you are describing.

We could try to go with a compromise: 
* Use Lua if it works, if it fails make a fallback to a rust function. 
* After we start the service, we could also run a set of tests to check the sanity of lua scripts.

What do you think?

**Comment by gferon** [comment]
I have no preference, but I kind of prefer having to deal with a single programming language here.
We could definitely bring this back if we plan on adding lots of customization capabilities (user input Lua scripts?).

**Comment by fbenkstein** [comment]
@boxdot The problem as far as I can tell is that `cargo install` cannot install auxilially files so you have to install them manually.  I think this is currently being discussed by the `cargo` team.  My suggestion is that we simply expect the files to exist at a specific location and if they're not there we write them out using `include_bytes!` to source them into the executable.

**Comment by fbenkstein** [comment]
Wow, somebody pushed to the wrong branch?

**Comment by gferon** [comment]
@fbenkstein would you be willing to add proper error handling in the `format_msg` function?

I think this is my main problem with this feature.

**Comment by gferon** [comment]
I don't know why, but I cannot assign those issues to you.

**Comment by boxdot** [comment]
I guess we are not doing it anymore. So I close it. If we need any changes from here, we can cherry-pick them.

**Pull request closed without merging**
