### PR TITLE
Improving output of help for flags

### PR DESCRIPTION
**Pull request by devcooch**
Did not test locally as it's not documented how to run the tests.

### CODE REVIEW

**Comment by fbenkstein** [comment]
There's a `HACKING.md` file which describes how to run the tests:

```
behave
```

The tests are in the `tests/features` folder.  There's no test for this particular feature yet but if there was it should go into `tests/features/formatting.feature`.

**Comment by devcooch** [comment]
@fbenkstein I don't think it's enough. When I run `behave` I get the following error:
`HOOK-ERROR in before_all: ValueError: Failed to reach Gerrit at http://localhost:8080`

**Comment by fbenkstein** [comment]
@devcooch: yes, sorry.  You need to have a testing instance of Gerrit running in the background or another terminal.  You can use `docker-compose up gerrit` or `./testing/run-gerrit.sh`.

**Comment by boxdot** [comment]
Thanks!

**Pull request merged**
